### ISSUE TITLE
1.48.5: test_file_architecture_26 and test_xfs_growfs_0 failing

### ISSUE THREAD

**Issue by dvzrv** [libguestfs/libguestfs#100]
Hi! While packaging 1.48.5 for Arch Linux I ran into these two tests failing:
`test_file_architecture_26` and `test_xfs_growfs_0`.

[libguestfs-1.48.5-1-x86_64-build.log](https://github.com/libguestfs/libguestfs/files/10069034/libguestfs-1.48.5-1-x86_64-build.log)
[libguestfs-1.48.5-1-x86_64-check.log](https://github.com/libguestfs/libguestfs/files/10069035/libguestfs-1.48.5-1-x86_64-check.log)
[test-suite.log](https://github.com/libguestfs/libguestfs/files/10069046/test-suite.log)

**Comment by dvzrv** [comment]
> Is it reproducible if you run `file ./test-data/files/lib-i586.so.zst` on the host?

That seems fine (outside of the build environment):
```
file ./test-data/files/lib-i586.so.zst
./test-data/files/lib-i586.so.zst: Zstandard compressed data (v0.8+), Dictionary ID: None
```

**Comment by rwmjones** [comment]
Thanks.  Another thing to try would be something like:
```
$ ./run virt-rescue --ro -a test-data/test.iso -m /dev/sda

><rescue> find / -name '*.zst'
/sysroot/lib-i586.so.zst
><rescue> file -bsL /sysroot/lib-i586.so.zst
Zstandard compressed data (v0.8+), Dictionary ID: None
```

I expect that the last command may segfault for you inside the appliance, although I don't know why.

**Comment by dvzrv** [comment]
Hmm, that actually also went fine (in the build environment):

```
><rescue> file -bsL /sysroot/lib-i586.so.zst
Zstandard compressed data (v0.8+), Dictionary ID: None
```

**Comment by dvzrv** [comment]
During the build the test still fails though.
Is there a way for me to disable it for now?

btw: Your patch for `test_xfs_growfs_0` works as intended! Thanks!

**Comment by dvzrv** [comment]
Ah, I guess it would be `export SKIP_TEST_FILE_ARCHITECTURE_26=1`

**Comment by rwmjones** [comment]
Right, although I'm confused/worried why that test is failing ...

**Comment by dvzrv** [comment]
Let me know if I can test further things. Build/test always takes quite a while (even on my machine) but I can try again tomorrow.

**Comment by Toolybird** [comment]
It's probably the 'z' switch:
```
><rescue> file -zbsL /sysroot/lib-i586.so.zst
Bad system call
```
Arch compiles its "file" utility with seccomp support whereas it appears Fedora does not. At least that's what it looks like after checking the koji build log:
```
checking for seccomp_init in -lseccomp... no
```
Is that intentional by Fedora?

**Comment by rwmjones** [comment]
Oh, well spotted!  This could well be the case.  Let me compile the Fedora package with seccomp support to see if I can reproduce the problem ...

**Comment by rwmjones** [comment]
Yes, I can reproduce this.  In fact this is both a bug upstream (in the seccomp support) *and* in Fedora.  I will file bugs for both.

**Comment by rwmjones** [comment]
Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=2148753

**Comment by rwmjones** [comment]
Upstream bug: https://bugs.astron.com/view.php?id=406

**Comment by Toolybird** [comment]
re: the upstream report...not sure that'll fly as it's kinda expected when the sandbox is in effect. See the man page [1].

The libguestfs test can be made to pass if the "file" call on line 46 of daemon/file.ml is changed from "-zb" to "-zbS", but I'm not sure if that's what you really want.

[1] https://man.archlinux.org/man/file.1.en#SECURITY
