### ISSUE TITLE
virt-builder --update needs to use zypper dup

### ISSUE THREAD

**Issue by olafhering** [libguestfs/libguestfs#101]
`virt-builder opensuse-tumbleweed --update` calls `zypper up`. As a result zypper complains about this "weak" update. This might be visible only if called with `--verbose`.

For Tumbleweed it is required to run `zypper dup|dist-upgrade` to make sure each and every installed package is eventually aligned with the packages provided in the latest variants in today's repositories.

There is no downside to use `zypper dup` with every other dist which uses `libzypp` under the hood. While all the documentation claims to use the `up` or `patch` commands, `dup` will work equally well.

**Comment by rwmjones** [comment]
If it OK to make a change like this (in the libguestfs-common submodule):
```
$ git diff
diff --git a/mlcustomize/guest_packages.ml b/mlcustomize/guest_packages.ml
index 7c29a2a..e4c3cc5 100644
--- a/mlcustomize/guest_packages.ml
+++ b/mlcustomize/guest_packages.ml
@@ -100,7 +100,7 @@ let update_command package_management =
   | "urpmi" ->  "urpmi --auto-select"
   | "xbps" ->   "xbps-install -Suy"
   | "yum" ->    "yum -y update"
-  | "zypper" -> "zypper -n update -l"
+  | "zypper" -> "zypper -n dup -l"
 
   | "unknown" ->
     error_unknown_package_manager "--update"
```

This means every `--update` operation will run `zypper -n dup -l` instead of `up`.

**Comment by rwmjones** [comment]
I tried that command on tumbleweed and it seems to work ok for me.

**Comment by olafhering** [comment]
Yeah, looks like the correct change. I did not find the code, thanks for finding the correct spot.
