### ISSUE TITLE
I want to change the sid of windows  guest (qemu guest)，what can i do?

### ISSUE THREAD

**Issue by yangni2017** [libguestfs/libguestfs#112]
### env
* Operating system: centos8
* OS/kernel version: 5.10.0-60.18
* Architecture: x86
* QEMU flavor: qemu-system-x86_64
* QEMU version: 6.2.0
* LIBVIRT: libvirt 6.2.0
* soft :   libguestfs-1.40.2-19.oe2203

As we know,if a guest clone form other guest, the sid is the same. So, I want to change the sid use libguestfs tool, i see the man page of "virt-sysprep" seem have some introductions , but the man page has not detailed methodology is provided? Or libguestfs  has other to chang the windows sid.

![image](https://user-images.githubusercontent.com/24664071/221733790-f747a858-6427-4113-a08e-7ec2c9bc03af.png)

**Comment by rwmjones** [comment]
It's not possible with the current tools, but it's something that would be good to provide. As I understand it, changing the SID is quite difficult.

**Comment by yangni2017** [comment]
ok,thanks a lot!
