### ISSUE TITLE
virt-sparsify spurious errors and behavior when GPT partition table is damaged.

### ISSUE THREAD

**Issue by jgilmore** [libguestfs/libguestfs#113]
I've been struggling to convert a hard drive to a sparse .qcow2 file on a different computer using the fuse filesystem sshfs.

Spurious errors I've seen include:
Rejecting the current directory as a valid target for "--tmp" with a "must be a directory, image, or block device"
mount --bind: Permission denied (As the superuser, this can happen even for root on fuse filesystems. Wasn't THAT a fun red herring to chase down.)
Ignoring "$TMPDIR" and creating the temporary .qcow2 file in /tmp/ ANYWAY. (Which is a bug in and of itself. If for some reason $TMPDIR doesn't work, it should error and stop, not create the temporary drive somewhere else instead.)
And one more that I can't remember the details of, as I was getting suspicious that it was something else entirely by that point.

After much trail and error, I finally figured out that the GPT partition table of my source drive was damaged. Fixing that made all the other errors just go away.

So, have fun with that. Maybe add a check for a corrupted partition table to the start? Would have been nice to get a coherent and meaningful error message from the start.

**Comment by rwmjones** [comment]
Is there a way to reproduce this?  Are you doing an in-place sparsification or a copying one (ie. using `--in-place` or not)?
