### ISSUE TITLE
Guestfish removes query string from URI

### ISSUE THREAD

**Issue by chintanrp** [libguestfs/libguestfs#116]
@rwmjones  - Were we able to resolve this bug posted few years ago? Because I see the issue still exists. Or do we have a workaround for this?
https://bugzilla.redhat.com/show_bug.cgi?id=1092583

**Comment by rwmjones** [comment]
The bug still exists AFAIK.

Nowadays it is easy to work around it using nbdkit, for example:
```
$ nbdkit curl 'https://download.fedoraproject.org/pub/fedora/linux/releases/38/Cloud/x86_64/images/Fedora-Cloud-Base-38-1.6.x86_64.qcow2?foo=bar' \
        --filter=cow \
        --run 'guestfish -x --format=qcow2 -a $uri -i cat /etc/redhat-release'
```
