### ISSUE TITLE
Read support for MAME CHD format

### ISSUE THREAD

**Issue by RandomDude560** [libguestfs/libguestfs#117]
MAME CHD format can hold HDD or optical disk data which is used by many emulators e.g. dosbox-x.
It would be great to be able to easily mount CHD files without decompressing them first.

standalone CHD library
https://github.com/rtissera/libchdr

**Comment by rwmjones** [comment]
libguestfs just uses the Linux kernel and/or external block device support, it doesn't implement any block device or filesystem formats itself.  

As I understand it from a very brief flip through the code this is a block device format, and it would be excellent to support it in [nbdkit](https://gitlab.com/nbdkit/nbdkit).  It might even be able to use the library above.

With nbdkit support you could them open the disk with:

```
nbdkit chd image --run 'guestfish -a $uri ...'
```

However I am closing this bug as it's not something that we need to change libguestfs for.
