### ISSUE TITLE
Guestfish Disk format command failing

### ISSUE THREAD

**Issue by armanamjad** [libguestfs/libguestfs#118]
When trying to add a remote vhd disk image via https url, the disk format command is failing:

libguestfs: trace: disk_format "https://md-cvszr5ftrd5n.z5.blob.storage.azure.net/v1qpzw4dlh5x/abcd?sv=2018-03-28&sr=b&si=bf205e68-31d2-499e-bb14-23e59ae9dc5a&sig=baeDixq3vh4ymp3P7C7MS7JGRazuawgSzvS5U3dwQ2s%3D"
libguestfs: command: run: qemu-img --help | grep -sqE -- '\binfo\b.*-U\b'
libguestfs: command: run: qemu-img
libguestfs: command: run: \ info
libguestfs: command: run: \ -U
libguestfs: command: run: \ --output json
libguestfs: command: run: \ ./https://{REDACTED_URI}
qemu-img: Could not open './https://{REDACTED_URI}': Could not open './https://{REDACTED_URI}': No such file or directory
libguestfs: error: qemu-img info: https://{REDACTED_URI}: qemu-img info exited with error status 1, see debug messages above

**Comment by rwmjones** [comment]
What's the guestfish command?  It seems like you're trying to add a local file called "https:..."

You have to use `-a https://` (https://libguestfs.org/guestfish.1.html#a-https:-user-example.com-:port-disk.img)

**Comment by armanamjad** [comment]
> What's the guestfish command? It seems like you're trying to add a local file called "https:..."
> 
> You have to use `-a https://` (https://libguestfs.org/guestfish.1.html#a-https:-user-example.com-:port-disk.img)

Yeah I used this command: 
guestfish -a "https://{URI}" --ro

But I am trying to add a remote file using a Disk SAS URI and from the error it looks like it is trying to open it like a local file

**Comment by armanamjad** [comment]
Thanks, I will try out the add command. I was able to work around that issue by removing the disk format command from the disk create function and hardcoding the backing format as "vpc". That worked and I was able to run the launch command successfully, but inspect-os and mounting are both failing. List filesystems doesn't show any guid either:
><fs> list-filesystems
/dev/sda: unknown

Do you know if this could be because the format I chose is incorrect? It is a VHD file so I assumed vpc would work.

**Comment by rwmjones** [comment]
There's not really sufficient information available to tell, but it's possible that if you don't specify the right format then we would not be able to interpret the disk image at all.

**Comment by rwmjones** [comment]
One thing you might try is dumping the boot sector from inside guestfish to see if it looks sensible, ie:

```
pread-device /dev/sda 512 0 | hexdump -C
```

**Comment by armanamjad** [comment]
I was able to get this to work after specifying the format as raw: guestfish --ro --format=raw -a "https://{URI}" 
Thanks for your help!
