### ISSUE TITLE
libguestfs: error: extlinux: feature 'extlinux' is not available in this build of libguestfs.

### ISSUE THREAD

**Issue by sujitfulse** [libguestfs/libguestfs#12]
libguestfs: error: extlinux: feature 'extlinux' is not available in this build of libguestfs. Read 'AVAILABILITY' in the guestfs(3) man page for how to check for the availability of features.

I am getting this error, as, feature extlinux is not available. How to make it available to fix it ??

**Comment by sujitfulse** [comment]
[root@localhost yum.repos.d]# guestfish -a /dev/null run : supported
             acl yes
          augeas yes
      blkdiscard yes
blkdiscardzeroes yes
           btrfs yes
        extlinux no
          fstrim yes
           gdisk yes
            grub no
           hivex yes
         inotify yes
         journal yes
             ldm yes
       linuxcaps yes
     linuxfsuuid yes
    linuxmodules yes
     linuxxattrs yes
            luks yes
            lvm2 yes
           mdadm yes
           mknod yes
          ntfs3g yes
       ntfsprogs yes
        realpath yes
           rsync no
           scrub yes
         selinux yes
        syslinux no
          wipefs yes
             xfs yes
              xz yes
        zerofree yes

**Comment by rwmjones** [comment]
Closing since (a) we don't use this issue tracker and (b) this was already answered on IRC.  The answer is that ppc64le doesn't support syslinux.
