### ISSUE TITLE
dhclient EOLed

### ISSUE THREAD

**Issue by fundawang** [libguestfs/libguestfs#121]
https://github.com/libguestfs/libguestfs/blob/ca20f27cb0898c347e49b543a8acdfb0a8a8fa7e/appliance/init#LL115C1-L125C3

```
if test "$guestfs_network" = 1; then
    iface=$(ls -I all -I default -I lo /proc/sys/net/ipv4/conf)
    # Two workarounds for Ubuntu:
    touch /etc/fstab
    rm -f /etc/dhcp/dhclient-enter-hooks.d/resolved
    if dhclient --version >/dev/null 2>&1; then
        dhclient $iface
    else
        dhcpcd $iface
    fi
fi
```

As stated upstream[1], dhcp client is not maintained any more, and should not be used in production. Is there any progress removing it from init script?

[1]: https://www.isc.org/dhcp/

**Comment by rwmjones** [comment]
What's the alternative for setting up a DHCP interface?  I guess we can just use dhcpcd but I don't know what distros have that.

**Comment by fundawang** [comment]
networkmanager?

**Comment by rwmjones** [comment]
Hardly want to depend on a massive package that itself depends on Python.

**Comment by rwmjones** [comment]
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/FJHABX7WU6ZU2MRTPKWU2TTBVYZKZWG3/
