### ISSUE TITLE
Kernel 6.5.4 doesn't work with libguestfs

### ISSUE THREAD

**Issue by github2099** [libguestfs/libguestfs#126]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com/"
SUPPORT_URL="https://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

> virt-manager
> guestfs-tools

**Issue/Bug Description:**

When I run `$ sudo virt-sparsify --in-place -v vm.qcow` the process will stop at 
`Invalid ELF header magic: != \x7fELF insmod: init_module:virtio_snd.ko.zst: Invalid module format  supermin: waiting another 1024000000 ns for root UUID to appear  This usually means your kernel doesn't support virtio, or supermin was unable to load some kernel modules (see module loading messages above).`

**Steps to reproduce (if you know):**

cd into the folder containing .qcow
run `$ sudo virt-sparsify --in-place -v vm.qcow`

I tested with a fresh installation, problem still exists.
Further testing, there is issue with 6.5.4.. previous 6.2.6 doesn't have problem.

I tested with 
kernel 6.5.4 https://iso.pop-os.org/22.04/amd64/intel/35/pop-os_22.04_amd64_intel_35.iso
kernel 6.2.6 https://iso.pop-os.org/22.04/amd64/intel/28/pop-os_22.04_amd64_intel_28.iso

crossed posted from https://github.com/pop-os/pop/issues/3158

I tried to fall bacck to kernel 6.4.6 .. but it gives me the same error. I am thinking the issue existed back then, but I didn't notice.

**Comment by rwmjones** [comment]
This is fixed upstream in supermin:

https://bugzilla.redhat.com/show_bug.cgi?id=1990209 
https://github.com/libguestfs/supermin/commit/4306a131c6cde92f8d0a2dd9376f4096ee538eff

**Comment by github2099** [comment]
Hi @rwmjones , do you know which version of libguestfs includes the fixes?
I'm on 1.46.1

**Comment by rwmjones** [comment]
None of them, as it's a bug/missing feature in supermin, not libguestfs.  You will need supermin 5.3.1 or later.

**Comment by github2099** [comment]
> None of them, as it's a bug/missing feature in supermin, not libguestfs. You will need supermin 5.3.1 or later.

Thanks for confirming, I have supermin 5.2.1, that might be the cause. Again, thanks for your time
