### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [libguestfs/libguestfs#131]
Dear @libguestfs team, @rwmjones, @lersek,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by rwmjones** [comment]
This is done now: https://github.com/libguestfs

**Comment by Neustradamus** [comment]
@rwmjones: Good job!

Happy New Year 2024!

You can add more informations about the project, links, logo, ...
- https://github.com/organizations/libguestfs/settings/profile

Please add you public in the organization, same for @lersek and the other members of the team:
- https://github.com/orgs/libguestfs/people

**Comment by rwmjones** [comment]
I've added some more details now.

**Comment by Neustradamus** [comment]
@rwmjones: Thanks!

Note: You have not showed you in public here (always in private):
- https://github.com/orgs/libguestfs/people
