### ISSUE TITLE
Read-only NBD using direct backend 

### ISSUE THREAD

**Issue by crabique** [libguestfs/libguestfs#135]
Hello!

In [NBD section](https://libguestfs.org/guestfs.3.html#network-block-device) of the documentation, it says that
> - The direct backend does not support readonly connections because of a bug in qemu: https://bugs.launchpad.net/qemu/+bug/1155677

However, the linked issue itself was closed in 2018, and the reasoning given there hints that it should now work. So I decided to test it and got the following results:
- When adding an NBD remotely (`add-drive-opts $EXPORT readonly:true protocol:nbd server:$IP:$PORT`) it fails with `qemu-img: Could not open './nbd:XXX:YYY:exportname=ZZZ': No such file or directory` in the debug trace
- The above works perfectly fine if I change it to `readonly:false`, but this requires the server to allow RW
- When adding an NBD from "local" file (via mounting it first with `nbdfuse --readonly`) it also works perfectly fine on just read-only access, but it's a really hacky solution and I can't make it work reliably (different fuse versions, no good way to ready-check the nbdfuse mount etc)

So, the question is whether it's still a bug that should be reopened and this is still not possible?

I want to attach read-only remote NBD exports but I also need to be able to `e2fsck forceall:true` them, so guestfish seemed like a perfect solution for this because of CoW overlay. Maybe I am missing something and just doing it wrong?

Any response would be appreciated, thank you!

**Comment by rwmjones** [comment]
So it all works for me fine, both with 'direct' and 'libvirt' backends, eg:

```
$ nbdkit -fvr memory 1G &
$ LIBGUESTFS_BACKEND=direct guestfish 

Welcome to guestfish, the guest filesystem shell for
editing virtual machine filesystems and disk images.

Type: ‘help’ for help on commands
      ‘man’ to read the manual
      ‘quit’ to quit the shell

><fs> add-drive-opts / readonly:true protocol:nbd server:localhost:10809 format:raw
><fs> run
><fs> 
```

Note the way this actually works is that libguestfs creates a qcow2 overlay backed by the NBD export.  All writes go to the qcow2 overlay and are discarded when libguestfs exits. Nothing is ever written to the NBD export.

```
$ qemu-img info -U /tmp/libguestfswOdaak/overlay1.qcow2
image: /tmp/libguestfswOdaak/overlay1.qcow2
file format: qcow2
virtual size: 1 GiB (1073741824 bytes)
disk size: 196 KiB
cluster_size: 65536
backing file: nbd:localhost:10809:exportname=/
backing file format: raw
Format specific information:
    compat: 1.1
    compression type: zlib
    lazy refcounts: false
    refcount bits: 16
    corrupt: false
    extended l2: false
Child node '/file':
    filename: /tmp/libguestfswOdaak/overlay1.qcow2
    protocol type: file
    file length: 192 KiB (197120 bytes)
    disk size: 196 KiB
```

What NBD server are you using?  `nbdkit` supports [CoW filters](https://libguestfs.org/nbdkit-cow-filter.1.html) itself so you wouldn't even need to rely on libguestfs support.

**Comment by crabique** [comment]
You are totally right 😞 

I now understand that I got confused by different handling of the `format` argument by different backends:
On direct backend without it I am getting the same error as I initially shared in the trace, and it never actually complains about the` format` being a required option:
```bash
$ LIBGUESTFS_BACKEND=direct guestfish

Welcome to guestfish, the guest filesystem shell for
editing virtual machine filesystems and disk images.

Type: ‘help’ for help on commands
      ‘man’ to read the manual
      ‘quit’ to quit the shell

><fs> add-drive-opts / readonly:true protocol:nbd server:localhost:10809
libguestfs: error: qemu-img info: nbd:localhost:10809:exportname=/: qemu-img info exited with error status 1.
To see full error messages you may need to enable debugging.
Do:
  export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
and run the command again.  For further information, read:
  http://libguestfs.org/guestfs-faq.1.html#debugging-libguestfs
You can also run 'libguestfs-test-tool' and post the *complete* output
into a bug report or message to the libguestfs mailing list.
```

But on libvirt backend, I get a proper error that I'm missing a required argument:
```bash
$ LIBGUESTFS_BACKEND=libvirt LIBGUESTFS_BACKEND_SETTINGS=force_tc guestfish

Welcome to guestfish, the guest filesystem shell for
editing virtual machine filesystems and disk images.

Type: ‘help’ for help on commands
      ‘man’ to read the manual
      ‘quit’ to quit the shell

><fs> add-drive-opts / readonly:true protocol:nbd server:localhost:10809
libguestfs: error: could not auto-detect the format when using a non-file protocol.
If the format is known, pass the format to libguestfs, eg. using the
‘--format’ option, or via the optional ‘format’ argument to ‘add-drive’.
```

For some reason with direct backend it works without format if the volume is file, so I never thought it could be the problem and once I gave up on direct, I moved on to libvirt backend, fixed what it complained about and thought those are just quirks specific to that backend, everything took forever with tcg but it worked.

> What NBD server are you using?  nbdkit supports [CoW filters](https://libguestfs.org/nbdkit-cow-filter.1.html) itself so you wouldn't even need to rely on libguestfs support.

Unfortunately, it's not nbdkit, I'm mounting [Benji NBD](https://benji-backup.me/restore.html#nbd-server), it has a custom Python implementation of NBD and very limited configuration.

Anyways, once I fixed everything livbirt backend didn't like, I just had to switch over back to direct and everything started working.

I'm sorry for creating a misleading issue and thank you very much for help @rwmjones ! 
P.S. I _just_ noticed that I wasn't  supposed to use this issue tracker at all, sorry for that too 😅
