### ISSUE TITLE
1.52.0: btrfs related c_api/tests are failing (unable to create quota group: Invalid argument)

### ISSUE THREAD

**Issue by dvzrv** [libguestfs/libguestfs#136]
Hi! :wave: 

When doing a rebuild of the package on Arch Linux I noticed five failing tests, that revolve around btrfs, e.g.:

```
libguestfs: error: btrfs_qgroup_create: /: ERROR: unable to create quota group: Invalid argument
FAIL: test_btrfs_qgroup_assign_0
```

I wonder if this is related to recent kernel or userland tooling upgrades.
Currently, I have to somehow disable these tests to be able to rebuild the package.

[test-suite.log](https://github.com/libguestfs/libguestfs/files/14472413/test-suite.log)

**Comment by dvzrv** [comment]
In the btrfs 6.7 release notes I can't find any breaking changes:
https://btrfs.readthedocs.io/en/latest/Kernel-by-version.html#jan-2024
https://btrfs.readthedocs.io/en/latest/Feature-by-version.html#x
(only the *new* feature `squota` has been added)

Initially we built the package against btrfs-progs-6.6.3-1-x86_64, which built and tested fine.

**Comment by rwmjones** [comment]
I can see the same thing (`btrfs-progs-6.7.1-1.fc41.x86_64`)

**Comment by rwmjones** [comment]
A one-line reproducer is:
```
$ guestfish -N part mkfs-btrfs /dev/sda1 : mount /dev/sda1 / : \
        btrfs-quota-enable / true : btrfs-qgroup-create 0/1000 /
libguestfs: error: btrfs_qgroup_create: /: ERROR: unable to create quota group: Invalid argument
```

**Comment by rwmjones** [comment]
It seems to be caused by the kernel version:

kernel-6.5.0-0.rc7 => NO error
kernel-6.7.3-200.fc39.x86_64 => NO error 
ernel-6.7.7-200.fc39.x86_64 => error
kernel-6.8.0-0.rc6.49.fc41.x86_64 => error

**Comment by heftig** [comment]
It's probably https://github.com/torvalds/linux/commit/0c309d66dacddf8ce939b891d9ead4a8e21ad6f0.

**Comment by heftig** [comment]
You're not allowed to manually create quota groups with a level of `0`. This is mentioned in `btrfs qgroup create --help` and also documented in the [`btrfs-qgroup` manpage](https://man.archlinux.org/man/core/btrfs-progs/btrfs-qgroup.8.en#QGROUP).

**Comment by rwmjones** [comment]
> It's probably [torvalds/linux@0c309d6](https://github.com/torvalds/linux/commit/0c309d66dacddf8ce939b891d9ead4a8e21ad6f0).

Yup, that's the one, thanks.
