### ISSUE TITLE
Cannot install libguestfs 1.31.19

### ISSUE THREAD

**Issue by jean-christophe-manciot** [libguestfs/libguestfs#14]
Compiled from github sources, packaged and installed:
"trying to overwrite '/usr/lib/x86_64-linux-gnu/perl/5.20.2/perllocal.pod', which is also in package git 1:2.6.0-1"
I'd like to avoid "dpkg -i --force-overwrite".

What should be done to overcome that incompatibility with git?

**Comment by libguestfs** [comment]
Please see my reply on the mailing list.

**Comment by libguestfs** [comment]
https://www.redhat.com/archives/libguestfs/2015-October/msg00308.html
