### ISSUE TITLE
inmutable /etc/resolv.conf

### ISSUE THREAD

**Issue by javier-angulo** [libguestfs/libguestfs#141]
Hello,

in the case where `/etc/resolv.conf` has the immutable attribute set, conversion via virt-v2v fails as it cannot be (temporary) renamed.

Snippet from virt-v2v-in-place log:
```
...
mount: /sysroot/sys/fs/selinux: mount point does not exist.
       dmesg(1) may have morelibguestfs: trace: v2v: command_lines = NULL (error)
virt-v2v-in-place: error: libguestfs error: command_lines: rename: /sysroot/etc/resolv.conf to /sysroot/etc/9t4pp3up: Operation not permitted
rm -rf -- '/tmp/v2vnbdkit.NH90Gm'
rm -rf -- '/tmp/v2v.LQtVMS'
libguestfs: trace: v2v: close
libguestfs: closing guestfs handle 0x55b4e39d1bb0 (state 2)
libguestfs: trace: v2v: internal_autosync
 information after failed mount system call.
renaming /sysroot/etc/resolv.conf to /sysroot/etc/9t4pp3up
guestfsd: error: rename: /sysroot/etc/resolv.conf to /sysroot/etc/9t4pp3up: Operation not permitted
...
```

Setting `/etc/resolv.conf` is arguably strange, but I wonder if this can be circumvented somehow.

**Comment by rwmjones** [comment]
See https://github.com/libguestfs/libguestfs/blob/c2f1825574d36fd93b1147dd31e487a3ac572e07/daemon/sh.c#L146

It should only happen if the network is enabled (`guestfs_set_network`), so the workaround would be to disable the network.  However virt-v2v always enables the network as it is necessary for various utilities we need to run.

**Comment by javier-angulo** [comment]
Thank you Richard.

We have found some cases (dozens) while converting a big number of VMs. My guess is the VM owners find annoying that DHCP changes resolv.conf, so they just make it immutable.
 
I was wondering if circumventing this would be an option to consider, I was thinking of

- in `set_up_etc_resolv_conf` storing the file attributes in case it is inmutable, removing then the inmutable attr
- restoring attributes in `free_resolver_state`

(Note that my skills in C are non-existant).
Maybe too much for just some corner cases?

Thanks.

**Comment by rwmjones** [comment]
I'm sympathetic, but this is a complex change to make and verify without having a Red Hat support case behind it.  As a work around I would just unset the immutable bit before conversion and set it afterwards.  If using something like MTV then you can run an Ansible Playbook before & after to do this kind of thing.

**Comment by javier-angulo** [comment]
Thank you for your help, Richard.  Very much appreciate it.

**Comment by javier-angulo** [comment]
Thank you for your help, Richard. Very much appreciate it.
