### ISSUE TITLE
Cannot install 1.31.19

### ISSUE THREAD

**Issue by jean-christophe-manciot** [libguestfs/libguestfs#15]
make[4]: Entering directory '/home/actionmystique/Program-Files/Ubuntu/Libguestfs/git-libguestfs/ocaml'
mkdir -p /usr/lib/ocaml
mkdir -p /usr/lib/ocaml/stublibs
ocamlfind install \
  -ldconf ignore -destdir /usr/lib/ocaml \
  guestfs \
  META *.so *.a *.cma *.cmi ./*.mli *.cmx *.cmxa
ocamlfind: Conflict with file: /usr/lib/ocaml/guestfs/mlguestfs.cmxa
Makefile:2128: recipe for target 'install-data-hook' failed
make[4]: *** [install-data-hook] Error 2
make[4]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Libguestfs/git-libguestfs/ocaml'
Makefile:1987: recipe for target 'install-data-am' failed
make[3]: *** [install-data-am] Error 2
make[3]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Libguestfs/git-libguestfs/ocaml'
Makefile:1935: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Libguestfs/git-libguestfs/ocaml'
Makefile:1829: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Libguestfs/git-libguestfs'
Makefile:2295: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by libguestfs** [comment]
Hi, please don't open github issues.  Send email to the mailing list (there is no need to subscribe): libguestfs@redhat.com.  You will need to post the complete output.
