### ISSUE TITLE
[RFE] Provide a more recent stable fixed appliance on libguestfs.org

### ISSUE THREAD

**Issue by lukts30** [libguestfs/libguestfs#156]
Could this project provide a more recent build of `libguestfs-make-fixed-appliance` on https://download.libguestfs.org/binaries/appliance/ ?

Nixpkgs [depends on this appliance](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/libraries/libguestfs/appliance.nix) as there is no support for nix as a package driver in supermin.
The current situation is particularly problematic because the host running the libguestfs toolset is newer than the `guestsfd` running in the latest available **stable** appliance (1.46.0), resulting in a bunch of `dispatch_incoming_message: unknown procedure number errors`.

So a appliance-1.54.0 would be really helpful.

**Comment by rwmjones** [comment]
OK I uploaded `appliance-1.54.0` built using the latest libguestfs on Fedora 40.

**Comment by lukts30** [comment]
Thanks a lot.

An additional question: From my experience (RPC error) I already inferred that the appliance should not be older than the host side tooling.
But is it ok for appliance to be newer than the host side tooling or should it always be updated in locksep?

**Comment by rwmjones** [comment]
The protocol hasn't changed in 10+ years, and it allows the appliance and the library to be mixed freely.  The only thing that can "go wrong" is that there are missing procedure numbers if you call an older appliance from a newer library.  Newer appliance and older library shouldn't be a problem under any circumstance I can think of.
