### ISSUE TITLE
How to write conditional statement in guestfish script?

### ISSUE THREAD

**Issue by RadxaYuntian** [libguestfs/libguestfs#163]
Some [commands](https://libguestfs.org/guestfish.1.html#exists) return true or false. Is there a way to run different guestfish commands based on this output? I can't find if-else in the man page.

**Comment by rwmjones** [comment]
guestfish isn't very good for complicated scripting.  I suggest using libguestfs from Python instead, as in these examples: https://libguestfs.org/guestfs-python.3.html

**Comment by RadxaYuntian** [comment]
This was for an intermediate script. In the end I use jsonnet as a guestfish template with pre-determined configuration, and avoided runtime logic.
