### ISSUE TITLE
Cannot compile 1.31.28

### ISSUE THREAD

**Issue by jean-christophe-manciot** [libguestfs/libguestfs#18]
**I had no such issue with 1.31.26**.
The packages which "cannot be authenticated" are already installed.

WARNING: The following packages cannot be authenticated!
  adduser base-files bash bsdmainutils cryptsetup debconf dpkg e2fsprogs fuse grub-common initramfs-tools initscripts insserv iproute2
  isc-dhcp-client kmod libaudit-common libc-bin libc6 libldap-2.4-2 libmagic1 libpam-modules libsemanage-common lvm2 mdadm mountall mtools
  openssh-client passwd plymouth procps reiserfsprogs rsync systemd sysv-rc tar udev util-linux uuid-runtime vim-common vim-tiny wget nilfs-tools
  zfs-fuse libgssapi-krb5-2
E: Some packages could not be authenticated
supermin: cd '/tmp/supermin0bbd7b.tmpdir/7e3rkfd7' && /usr/bin/apt-get  download 'bsdmainutils' 'cryptsetup' 'iproute2' 'isc-dhcp-client' 'libc-bin' 'mtools' 'nilfs-tools' 'openssh-client' 'reiserfsprogs' 'systemd' 'vim-tiny' 'zfs-fuse' 'uuid-runtime' 'bash' 'e2fsprogs' 'kmod' 'lvm2' 'mdadm' 'procps' 'rsync' 'tar' 'udev' 'util-linux' 'libc6' 'debconf' 'initramfs-tools' 'plymouth' 'libmagic1' 'grub-common' 'dpkg' 'fuse' 'libgssapi-krb5-2' 'adduser' 'passwd' 'sysv-rc' 'vim-common' 'base-files' 'initscripts' 'wget' 'mountall' 'libpam-modules' 'libaudit-common' 'insserv' 'libldap-2.4-2' 'libsemanage-common': command failed, see earlier errors
Makefile:1906: recipe for target 'stamp-supermin' failed
make[2]: *** [stamp-supermin] Error 1
make[2]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Libguestfs/git-libguestfs/appliance'
Makefile:1843: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/actionmystique/Program-Files/Ubuntu/Libguestfs/git-libguestfs'
Makefile:1754: recipe for target 'all' failed
make: *** [all] Error 2

Whole log: 
[Compiling 1.31.28.txt](https://github.com/libguestfs/libguestfs/files/43693/Compiling.1.31.28.txt)

**Comment by rwmjones** [comment]
We don't accept bug reports via github.  I will post your log on the mailing list shortly.
