### ISSUE TITLE
RFE: make virt-builder parse format=raw|qcow2 in repo definitions and add --format=auto option

### ISSUE THREAD

**Issue by ryran** [libguestfs/libguestfs#19]
Hi there.

The repo definition at [libguestfs.org/download/builder/index](http://libguestfs.org/download/builder/index) contains `format=raw` data for each template, e.g.:

```
[centos-6]
name=CentOS 6.6
osinfo=centos6.6
arch=x86_64
file=centos-6.xz
revision=6
checksum=fc403ea3555a5608a25ad30ce2514b67288311a7197ddf9fb664475820f26db2bd95a86be9cd6e3f772187b384a02e0965430456dd518d343a80457057bc5441
format=raw
size=6442450944
compressed_size=199265736
expand=/dev/sda3
notes=CentOS 6.6
```

It seems that `virt-builder` doesn't do anything with that metadata. It's completely missing from the long and json list-formats.

According to `man virt-builder`, it always assumes `--format raw`. Why? I've built my own repo with all xz-compressed qcow images and it seems crazy to me that `virt-builder` can't auto-detect this based on `format=qcow2`.

Halp!

I'd love to see:

* Make `format` a valid field that virt-builder pays attention to and includes in long & json output

That would be enough for me and my app, but I'd recommend continuing on and doing:

* Either change the default behavior to look for `format=qcow2|raw` in the template definition if `--format` isn't specified, or if you're unhappy changing the behavior, add `--format=auto` as an option.

**Comment by rwmjones** [comment]
Hi - I have copied this issue to the mailing list and will reply there shortly.

https://www.redhat.com/archives/libguestfs/2015-December/thread.html

**Comment by ryran** [comment]
Mmm. Okay. That's kind of a bummer, but I guess each project is different.
