### ISSUE TITLE
RFE: virt-builder ability to print definition for single template (new option or expand --notes)

### ISSUE THREAD

**Issue by ryran** [libguestfs/libguestfs#20]
The `virt-builder --notes <TEMPLATE>` command is nice, but I really wish it printed the full template definition, e.g., something like this:

```
$ virt-builder --notes centos-7.0

[centos-7.0]
name=CentOS 7.0
osinfo=centos7.0
arch=x86_64
file=centos-7.0.xz
checksum=cf9ae295f633fbd04e575eeca16f372e933c70c3107c44eb06864760d04354aa94b4f356bfc9a598c138e687304a52e96777e4467e7db1ec0cb5b2d2ec61affc
format=raw
size=6442450944
compressed_size=213203844
expand=/dev/sda3
notes=CentOS 7.0
 
This CentOS image contains only unmodified @Core group packages.

It is thus very minimal.  The kickstart and install script can be
found in the libguestfs source tree:

builder/website/centos.sh
```

Or maybe it could be like `virt-builder --list-format long --list` (all prettified) but only for a particular template.

I think normal users need this option to be able to check the `osinfo=` value for use with `virt-install` without having to scroll/grep through all their templates.

That said, for an app I'm writing I also wish `virt-builder --list-format json --list` could zero in on a particular template as well but now I know I'm askin' crazy.

**Comment by rwmjones** [comment]
Hi - I have copied this issue to the mailing list and will reply there shortly.

https://www.redhat.com/archives/libguestfs/2015-December/thread.html
