### ISSUE TITLE
RFE: virt-builder new option (--offline maybe) to allow running only from cache

### ISSUE THREAD

**Issue by ryran** [libguestfs/libguestfs#21]
I love virt-builder. It's great.

However, I don't always have internet access. Further, some of my repos are on private networks and I don't always have the appropriate VPN established to see them.

I wish virt-builder had an option that allow you to skip checking in with your remote repos and only use cache. I think that would be a huge win.

**Comment by rwmjones** [comment]
Hi - I have copied this issue to the mailing list and will reply there shortly.

https://www.redhat.com/archives/libguestfs/2015-December/thread.html
