### ISSUE TITLE
virt-v2v: error: libguestfs error: selinux_relabel: : Success

### ISSUE THREAD

**Issue by baozizhenmeixian** [libguestfs/libguestfs#22]
when i use **rel7 virt-v2v** to convert all the **linux** system ,this problem appeal: **virt-v2v: error: libguestfs error: selinux_relabel: : Success**, i do not know how to fix it .

guestfsd: main_loop: proc 467 (selinux_relabel) took 1.76 seconds
libguestfs: trace: v2v: s**elinux_relabel = -1 (error)**
virt-v2v: **error: libguestfs error: selinux_relabel: : Success**
rm -rf '/var/tmp/ova.Q8TNG6'
rm -rf '/var/tmp/null.fkFo25'
libguestfs: trace: v2v: close

**Comment by rwmjones** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1374232
