### ISSUE TITLE
virt-p2v-make-disk not making disk

### ISSUE THREAD

**Issue by mlanner** [libguestfs/libguestfs#25]
I've used the following commands trying to make a P2V disk to boot from:

```
# virt-p2v-make-disk -o /dev/sdb --inject-ssh-identity id_rsa_p2v
# virt-p2v-make-disk -o /dev/sdb centos-7.3 --inject-ssh-identity id_rsa_p2v
# virt-p2v-make-disk -o p2v/p2v.img centos-7.3 --inject-ssh-identity id_rsa_p2v
```

... on both CentOS 7.3 and Ubuntu 16.04, including from a bare metal machine to a USB drive, from a VM to a .img, as well as from a container to .img, and none of them seem to work. It downloads the base image, uncompresses it, and finally tries to open it. But that's where it stops:

```
root@p2v:~# virt-p2v-make-disk -o p2v/p2v.img centos-7.3 --inject-ssh-identity id_rsa_p2v
[   1.6] Downloading: http://libguestfs.org/download/builder/centos-7.3.xz
################################################################## 100.0%
[ 223.9] Planning how to build this image
[ 223.9] Uncompressing
[ 235.7] Opening the new disk 
...
```

An image file is created:

```
root@p2v:~/p2v# ll -h
total 1.1G
drwxr-xr-x  2 root root 4.0K Jan 28 16:19 ./
drwx------ 12 root root 4.0K Jan 28 16:15 ../
-rw-r--r--  1 root root 6.0G Jan 28 16:20 p2v.img
```

Even after leaving the process running for hours and hours, nothing seems to happen.

Any thoughts?

**Comment by rwmjones** [comment]
-> mailing list: https://www.redhat.com/archives/libguestfs/2017-January/msg00135.html
