### ISSUE TITLE
not able to 'make quickcheck' 

### ISSUE THREAD

**Issue by amita4581** [libguestfs/libguestfs#26]
Hi
i am trying to install libguestfs on linux distro (ubuntu 15.10). and following the below link
http://libguestfs.org/guestfs-building.1.html
- at make stage it suggest below command and retry 'make'
rm po-docs/podfiles; make -C po-docs update-po  
- i run above command and re 'make' successfully. however i am not able to get ' make quickcheck' through. the error output is attached with this query.

 any help will be appreciated.

[make-quickcheck-fails.docx](https://github.com/libguestfs/libguestfs/files/792490/make-quickcheck-fails.docx)

**Comment by rwmjones** [comment]
Please read: http://libguestfs.org/guestfs-faq.1.html#where-can-i-get-the-latest-binaries-for
