### ISSUE TITLE
how to create localenv

### ISSUE THREAD

**Issue by pahome** [libguestfs/libguestfs#27]
I want to build libguestfs from github.
And I read http://libguestfs.org/guestfs-building.1.html#local-files, and I want to remove the prefix 'git'. it confused me.
But when I enter
```
. localenv
 ./autogen.sh \
     -C \
     --enable-werror \
     "$@"
```
it doesn't show localenv and I didn't see localconfigure existing.
why

**Comment by rwmjones** [comment]
Answered in this thread on the mailing list: https://www.redhat.com/archives/libguestfs/2017-July/msg00334.html
