### ISSUE TITLE
virt-v2v-copy-to-local failed if dd does not support status=progress

### ISSUE THREAD

**Issue by zhujinhe** [libguestfs/libguestfs#31]
If dd does not support status=progress,  copy process will abort at the end. This is totally misguided.
We can use -q as a workaround in this circumstance, but it is frightening to newbee like me. Maybe we should improve this.

suspicion：
```
       if shell_command cmd <> 0 then
         error (f_"ssh copy command failed, see earlier errors");
```

detail：
```
shell > virt-v2v-copy-to-local -v -ic xen+ssh://myxen_server guest
[   0.0] Fetching the remote libvirt XML metadata ...
[   1.6] Parsing the remote libvirt XML metadata ...
[   1.6] Copying remote disk 1/2 to guest-disk1
dd: invalid status flag: ‘progress’
Try 'dd --help' for more information.
40960+0 records in
40960+0 records out
42949672960 bytes (43 GB) copied, 876.05 seconds, 49.0 MB/s
virt-v2v-copy-to-local: error: ssh copy command failed, see earlier errors

```

**Comment by libguestfs** [comment]
Moved discussion to the mailing list:

https://www.redhat.com/archives/libguestfs/2018-June/msg00049.html

We don't use github for issues.

**Comment by bersace** [comment]
@libguestfs you can disable issue in project settings.
