### ISSUE TITLE
OpenStack support

### ISSUE THREAD

**Issue by kedorlaomer** [libguestfs/libguestfs#38]
According to the manpage,

> Virt-p2v converts a physical machine to run virtualized on KVM, managed by libvirt, OpenStack, oVirt, Red Hat Virtualisation (RHV), or one of the other targets supported by virt-v2v(1).

In fact, `openstack` is one of the targets of `virt-v2v`. According to the file `p2v/conversion.c`, function `generate_wrapper_script`, the output mode of `virt-v2v` can be set to `glance`. The manpage of `virt-v2v` claims 

> only -o openstack should be used normally.

But even if `-o glance` was appropriate, there's no provision for setting additional command line flags such as `-oo …` in order to set up the server id, authentication and other conversion options.

Does the conversion to OpenStack work in any setup? Has it reportedly ever worked? What needs to be done to get it working?

**Comment by rwmjones** [comment]
We don't use this proprietary bug tracker.  I've answered your question on our mailing list: https://www.redhat.com/archives/libguestfs/2019-June/msg00070.html
