### ISSUE TITLE
Can virt-v2v-copy-to-local be used?

### ISSUE THREAD

**Issue by asmi10** [libguestfs/libguestfs#41]
Hello Currently I am using virt-v2v-copy-to-local on SLES for fetching disks from vmware ESXI hosts and converting them to kvm, it works fine so far. But I see this tool status is deprecated in github. 
Should I expect any possible issue with this tool?

**Comment by rwmjones** [comment]
https://www.redhat.com/archives/libguestfs/2019-August/msg00310.html
