### ISSUE TITLE
virt-v2v-copy-to-local is failing:cannot  find libvirt domain '<guestname>': Domain not found: No domain with name

### ISSUE THREAD

**Issue by asmi10** [libguestfs/libguestfs#42]
I am getting below error with virt-v2v-copy-to-local while copying the guest disk from remote esxi server to local.

:/infrastructure/kvm # virt-v2v-copy-to-local --debug-gc --verbose --password-file passfile -ic esx://root@<esxi>?no_verify=1 <guest>
virt-v2v-copy-to-local: libguestfs 1.32.4 (x86_64)
[   0.0] Fetching the remote libvirt XML metadata ...
virt-v2v-copy-to-local: error: internal error: invalid argument: cannot 
find libvirt domain '<guest>': Domain not found: No domain with name 
'<guest>'

If reporting bugs, run virt-v2v-copy-to-local with debugging enabled and 
include the complete output:

  virt-v2v-copy-to-local -v -x [...]

The guest is powered off and exists on esxi server, how exactly this tool dumps xml file of guest hosted in esxi server? Does it parse the guest vmx file on esxi host and dump it to local server?

**Comment by asmi10** [comment]
Issue has been solved, please ignore.

**Comment by sabrinesoltani** [comment]
> Issue has been solved, please ignore.
I want to know how could you resolve the problem 'cause I have the same issue. Thanks in advance

**Comment by rwmjones** [comment]
The copy-to-local tool has been removed from virt-v2v.
