### ISSUE TITLE
Have virt-sysprep to cleanup /etc/hosts

### ISSUE THREAD

**Issue by lzap** [libguestfs/libguestfs#44]
Hello Rich!

We had a request in Foreman to do cleanup `/etc/hosts` in our finish template (something like cloud-init but over ssh for those who don't use it). I closed the request with reference to the `virt-sysprep` tool but shortly after I started digging if the tool actually touches `/etc/hosts` and I am actually unable to find this.

However it does cleanup hostname from ifcfg scripts: https://github.com/libguestfs/libguestfs/blob/master/sysprep/sysprep_operation_net_hostname.ml. Therefore I am raising this ticket to consider also cleaning up `/etc/hosts`. It does make a lot of sense.

Thanks!

**Comment by rwmjones** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1809480

Hi Lukáš, as we don't use github for issues etc I filed an upstream bug, see link above.  Do you have a better idea about what entries exactly we'd remove/change in `/etc/hosts`?  It'd be good to add some examples of the sorts of changes you mean to the BZ.

**Comment by lzap** [comment]
Absolutely, thanks.
