### ISSUE TITLE
[Golang binding issue] StatNS struct fields are unexported

### ISSUE THREAD

**Issue by anemade** [libguestfs/libguestfs#53]
I am using the [stable release](https://download.libguestfs.org/1.42-stable/) for libguestfs golang binding.

**Issue**
I am trying to get the stats for some files(Located inside the disk) using the following function

```
func (g *Guestfs) Statns (path string) (*StatNS, *GuestfsError) {
    if g.g == nil {
        return &StatNS{}, closed_handle_error ("statns")
    }

    c_path := C.CString (path)
    defer C.free (unsafe.Pointer (c_path))

    r := C.guestfs_statns (g.g, c_path)

    if r == nil {
        return &StatNS{}, get_error_from_handle (g, "statns")
    }
    defer C.guestfs_free_statns (r)
    return return_StatNS (r), nil
}
```

This function is returing the address of the StatNS struct.  Following is the struct definition

```
type StatNS struct {
    st_dev int64
    st_ino int64
    st_mode int64
    st_nlink int64
    st_uid int64
    st_gid int64
    st_rdev int64
    st_size int64
    st_blksize int64
    st_blocks int64
    st_atime_sec int64
    st_atime_nsec int64
    st_mtime_sec int64
    st_mtime_nsec int64
    st_ctime_sec int64
    st_ctime_nsec int64
    st_spare1 int64
    st_spare2 int64
    st_spare3 int64
    st_spare4 int64
    st_spare5 int64
    st_spare6 int64
}

```

Because of the unexported fields, I can not check the stat in my code and I don't see any getter functions for the same.

**Expected behavior**
All StatNS struct fields should be exported or some getter functions should be there.

**Comment by rwmjones** [comment]
Imagine I know or care nothing about golang.  What change needs to be made to the struct?

**Comment by anemade** [comment]
@rwmjones Changing struct would be easy in my opinion. else, need to write the getter method for each and every field in the struct. 
If we can export the struct fields then It should solve my issue but I am really not sure if the fields are intentionally unexported.
Right now I am anyways using the workaround by writing some getter methods in the same package(`guestfs.go` from the stable release).

**Comment by rwmjones** [comment]
Again, imagining I know nothing, what change needs to be made to the code to export the whole struct?

**Comment by rwmjones** [comment]
So it seems as if what we need to do is capitalize the field names and then they should be accessible.  I'll see how easy that is.

**Comment by anemade** [comment]
Yes. I was replying the same

```
type StatNS struct {
    St_dev int64
    St_ino int64
    St_mode int64
    St_nlink int64
    St_uid int64
    St_gid int64
.
.
.
```

**Comment by rwmjones** [comment]
I added this commit: https://github.com/libguestfs/libguestfs/commit/3743cc89f6d0222b42e13ff955fbf088711d1664

The tests are failing with a strange error, but it seems unrelated to this change:
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
libguestfs.org/guestfs.(*Guestfs).Internal_test.func7(0xc000010028, 0x1faee70, 0x1fadf90, 0xc000010050, 0xc000000000, 0x0, 0x0, 0x1fae8c0, 0x1fa95f0, 0x1fa9610, ...)
	/home/rjones/d/libguestfs/golang/src/libguestfs.org/guestfs/guestfs.go:6667 +0xaf
libguestfs.org/guestfs.(*Guestfs).Internal_test(0xc000010028, 0x4f23c4, 0x3, 0xc00005bbe8, 0xc00005baf8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/rjones/d/libguestfs/golang/src/libguestfs.org/guestfs/guestfs.go:6667 +0x3cc
main.main()
	/home/rjones/d/libguestfs/golang/bindtests.go:77 +0x148c
exit status 2
FAIL run-bindtests (exit status: 1)
```
