### ISSUE TITLE
Permissions Behave Differently Inside Mounted Filesystems

### ISSUE THREAD

**Issue by trisys3** [libguestfs/libguestfs#54]
https://stackoverflow.com/questions/64273334/test-x-in-mounted-filesystem

When I run `test -x` inside a mounted filesystem mounted with `guestmount`, with `root` because that's the only way I can access it, it returns `true` even when the file is not executable. The answerer said this is because of [this line](https://github.com/libguestfs/libguestfs/blob/d107f12ac9219ad2df4cfdeb6ef4e8623bcbb013/lib/fuse.c#L333-L352), which looks right. To me there's no danger except inconsistency, as I'm already root. I'm using a library, asdf that checks for executable and does something different from normal, which fails because the file isn't actually executable.

Both the answerer & I are having trouble building to submit a patch. I'm having trouble with the C compiler, is there any FAQ or anything I can refer to while I'm debugging?

**Comment by rwmjones** [comment]
Fixed in https://github.com/libguestfs/libguestfs/commit/3f4a529ab753bea43a9cef7f8aaed48a2be23e30

**Comment by trisys3** [comment]
Thanks for this, and I'm sorry again that I couldn't manage to get my own version of libguestfs to build properly.

Are you sure the read/write bits should stay the same? There could well be similar checks from other tools that behave buggily with the libguestfs behavior. I haven't checked read/write, only execute, I'm just bringing it up.

**Comment by trisys3** [comment]
Also, a whole lot of thanks to the answerer of my StackOverflow question, `that other guy`, for answering so quickly and for finding the exact file & line #s. I wasn't even sure if this was libguestfs or if it was standard behaviir for mounting on linux in general.

**Comment by rwmjones** [comment]
> Are you sure the read/write bits should stay the same? There could well be similar checks from other tools that behave buggily with the libguestfs behavior. I haven't checked read/write, only execute, I'm just bringing it up.

I don't know, but I made the minimal change to fix the observed problem and if anyone well reports realistic problems with r/w we can deal with those separately.
