### ISSUE TITLE
resize with ubuntu-20.04 

### ISSUE THREAD

**Issue by peterwillis** [libguestfs/libguestfs#63]
Is there something I am missing to resize the disk in the ubuntu-20.04 template?

```
# virt-builder ubuntu-20.04 --size 30G
[   0.8] Downloading: http://builder.libguestfs.org/ubuntu-20.04.xz
[   1.8] Planning how to build this image
[   1.8] Uncompressing
[  10.9] Resizing (using virt-resize) to expand the disk to 30.0G
virt-resize: error: /dev/sda5: partition not found in the source disk image 
(this error came from ‘--expand’ option on the command line).  Try 
running this command: virt-filesystems --partitions --long -a 
/var/tmp/vb7ee275.img

If reporting bugs, run virt-resize with debugging enabled and include the 
complete output:

  virt-resize -v -x [...]
```

Or:

```
# virt-list-partitions -lh ubuntu-20.04.img 
/dev/sda1 vfat 512.0M
/dev/sda2 unknown 1K
/dev/sda5 ext4 5.5G
# truncate -r ubuntu-20.04.img ubuntu-20.04-resized.img
# truncate -s +5G ubuntu-20.04-resized.img 
# virt-resize --expand /dev/sda5 ubuntu-20.04.img ubuntu-20.04-resized.img 
[   0.0] Examining ubuntu-20.04.img
virt-resize: error: /dev/sda5: partition not found in the source disk image 
(this error came from ‘--expand’ option on the command line).  Try 
running this command: virt-filesystems --partitions --long -a 
ubuntu-20.04.img

If reporting bugs, run virt-resize with debugging enabled and include the 
complete output:

  virt-resize -v -x [...]
```

The verbose log is attached.

[verbose.log](https://github.com/libguestfs/libguestfs/files/5943649/verbose.log)

**Comment by rwmjones** [comment]
Answered on the mailing list here: https://listman.redhat.com/archives/libguestfs/2021-February/msg00018.html

**Comment by peterwillis** [comment]
thank you

**Comment by trayla** [comment]
I ran into the same issue. Is there any workaround?

**Comment by numas** [comment]
I would also like to know if this can be resolved. Current ubuntu-20.04 image on builder.libguestfs.org is from 2021-01-28. Can a new image be made that doesn't use logical/extended partitions?

**Comment by juwalter** [comment]
worked for me: install 18.04 and then `do-release-upgrade` (after `virt-install`  and  `virsh start --console`) - not ideal, but did the job

**Comment by BrianRamsay** [comment]
This really seems to be a big oversight, that you can create an image with virt-builder that can't be resized with virt-resize.

**Comment by HarshKapadia2** [comment]
Hey @joruxs, I'm having trouble following [your answer](https://github.com/libguestfs/libguestfs/issues/63#issuecomment-1527214694). I tried multiple things, but couldn't get it working. Could you please provide the commands that you used if possible? Thank you!

**Comment by HarshKapadia2** [comment]
[This](https://github.com/libguestfs/libguestfs/issues/63#issuecomment-1584277420) worked with a few minor changes. Thank you so much for responding and for your promptness, @joruxs! I appreciate it.
