### ISSUE TITLE
Libguestfs-tools cannot be replaced with guestfs-tools

### ISSUE THREAD

**Issue by Potterli20** [libguestfs/libguestfs#64]
Libguestfs-tools cannot be replaced with guestfs-tools
![Screenshot_20210328-012315_Termux](https://user-images.githubusercontent.com/28734349/112728880-5d50a580-8f64-11eb-86fa-ad0a001adb29.png)

**Comment by rwmjones** [comment]
See discussion here: https://bodhi.fedoraproject.org/updates/FEDORA-2021-f76c3d5eef
