### ISSUE TITLE
Performance issue: "udevadm settle" is called three times for a single call of guestfs_download_offset()

### ISSUE THREAD

**Issue by mkawahito** [libguestfs/libguestfs#67]
I'm planning to use guestfs_download_offset() to read a part of /dev/sda. I made a micro-benchmark for it.
I found that a single 512-bytes read access takes **60msec**. It is very slow.

I investigated a reason of it. I found that "udevadm settle -E /dev/sda" is invoked 3 times and that these three calls take **57msec**.

The command udevadm is called from the beginning of is_device_parameter(), as shown below.
https://github.com/libguestfs/libguestfs/blob/047cf7dcd26e649d45e7e21a3b679bad0bb6c312/daemon/utils.c#L120

I have the following two questions:
- Can we defer calling udev_settle_file (device) after next two IFs? (That is, after Line 128) I tried it, and the performance was improved to **3msec**.
- Can we cache the result of is_device_parameter() and then use it for the other two calls?

**Comment by rwmjones** [comment]
Answered on the mailing list: https://listman.redhat.com/archives/libguestfs/2021-May/msg00099.html

**Comment by mkawahito** [comment]
Hi Rich,

Yes, I'd like to read a QCOW2 file. Using libnbd showed 0.03msec for my micro-benchmark. I'll use it. Thank you very much!
