### ISSUE TITLE
virt-v2v: error: internal error: invalid argument: cannot fetch XML description of guest ‘Guest_Name’: internal error: HTTP response code 404 for download from

### ISSUE THREAD

**Issue by sabrinesoltani** [libguestfs/libguestfs#68]
I have a problem when I use virt-v2v to migrate VMs from Vmware hypervisor to OLVM plateform.
The guest is powered off and exists on esxi server.

virt-v2v: error: internal error: invalid argument: cannot fetch XML
description of guest ‘Guest_name’: internal error: HTTP response
code 404 for download from " https://...."
If reporting bugs, run virt-v2v with debugging enabled and include the
complete output:

  virt-v2v -v -x [...]

**Comment by rwmjones** [comment]
See: https://listman.redhat.com/archives/libguestfs/2021-June/msg00164.html
