### ISSUE TITLE
guestunmount should not return before the image can be used by other vm

### ISSUE THREAD

**Issue by braindevices** [libguestfs/libguestfs#70]
If I understood correct, the libguestfs actually start a qemu vm under the hood. When I call guestunmount it unmounts the image then shutdown the vm. However, if I do this programmably, commonly it will fail due to this appliance vm is still using the image:
```
guestmount -d guest1 mnt
# do something with the image
guestunmount mnt
virsh start guest1
```
I have to add sleep between guestunmount and other command. However, this time interval is not certain, it can be quite long. So I propose to add some option to let the guestunmount only return after the qemu vm release the image. Is there any work around right now for this?

**Comment by rwmjones** [comment]
https://listman.redhat.com/archives/libguestfs/2021-August/msg00069.html

**Comment by braindevices** [comment]
@rwmjones I did not get, why this thread resolve this issue? That thread seems talking about different problem about the sync of write operation and I never use cache=none.
