### ISSUE TITLE
Provide a new "appliance" build based on 1.45.x

### ISSUE THREAD

**Issue by cjeanner** [libguestfs/libguestfs#74]
Hello there,

It would be really nice getting a new [appliance build](https://download.libguestfs.org/binaries/appliance/) in order to support newest CentOS Stream 9 virtual machines running on CentOS Stream 8. Currently, there are issues with the filesystem - the same kind of things already happened with "8 on 7" environment some years ago.

Thank you!

Cheers,

C.

**Comment by rwmjones** [comment]
Answered on the mailing list: https://listman.redhat.com/archives/libguestfs/2021-November/msg00141.html

**Comment by cjeanner** [comment]
Perfect, I'll test it now!
