### ISSUE TITLE
guestfs_copy_in fails with error: copy_in: tar subprocess failed: tar: .: file changed as we read it: errno 0

### ISSUE THREAD

**Issue by anemade** [libguestfs/libguestfs#75]
I am using libguestfs Golang binding APIs(version 1.44)
Followed this document https://libguestfs.org/guestfs-golang.3.html to create the disk, add the disk, format the partition,  launch the appliance and performing some copy_in and copy_out operations.

While doing copy_in, I am seeing this strange issue

`error: copy_in: tar subprocess failed: tar: .: file changed as we read it: errno 0`

This issue is not all time reproducible. It comes like 1 out of 10 runs. In my case, data is stable while doing copy_in. There is absolutely no change in the data while guestfs_copy_in operation going on.
Any leads to issue or anything that I need to understand for copy_in or copy_out?

**Comment by rwmjones** [comment]
-> mailing list https://listman.redhat.com/archives/libguestfs/2022-January/msg00187.html
