### ISSUE TITLE
virt-builder unable to create larger disks than default for Ubuntu 20.04

### ISSUE THREAD

**Issue by BrianRamsay** [libguestfs/libguestfs#76]
The `--size` parameter does not work when using `virt-builder` to create an image for Ubuntu 20.04. This is a real problem for an automated workflow.

I see issues #55 and #63 were related to this issue, but it has been over a year for both of them. Is there any plan for resolving or working around the logical partition issue?

**Comment by rwmjones** [comment]
It requires someone to work out how to modify the Ubuntu installer so it either uses GPT or uses MBR but doesn't use logical partitions.  No one has done this so it's not been fixed.
