### ISSUE TITLE
php tests fail on php > 8.0 due to missing arginfo declaration

### ISSUE THREAD

**Issue by dvzrv** [libguestfs/libguestfs#78]
Hi! When trying to build this project for Arch Linux in version 1.48.1 I ran the test suite.
This fails on the PHP tests, because the module does not declare arginfo:

[run-php-tests.sh.log](https://github.com/libguestfs/libguestfs/files/8575466/run-php-tests.sh.log)

**Comment by rwmjones** [comment]
Yup, known problem, needs someone to send patches.  See: https://bugzilla.redhat.com/show_bug.cgi?id=1935753

**Comment by dreirund** [comment]
> Yup, known problem, needs someone to send patches. See: https://bugzilla.redhat.com/show_bug.cgi?id=1935753

A patch seems to be [&nearr;&hairsp;here](https://gitlab.archlinux.org/archlinux/packaging/packages/libguestfs/-/raw/main/libguestfs-1.48.1-disable_php_tests.patch).

**Comment by rwmjones** [comment]
That patch disables the tests, fine as a downstream solution, but not a bug fix.
