### ISSUE TITLE
1.48.1: test_isoinfo_device_0 fails (iso_volume_id: CDROM)

### ISSUE THREAD

**Issue by dvzrv** [libguestfs/libguestfs#79]
Hi! When building 1.48.1 for Arch Linux (against qemu 7.0.0) I ran the test suite.

The test `test_isoinfo_device_0` fails with:

```
libguestfs: trace: isoinfo_device = <struct guestfs_isoinfo = iso_system_id: LINUX, iso_volume_id: CDROM, iso_volume_space_size: 2495, iso_volume_set_size: 1, iso_volume_sequence_number: 1, iso_logical_block_size: 2048, iso_volume_set_id: , iso_publisher_id: , iso_data_preparer_id: , iso_application_id: MKISOFS ISO9660/HFS/UDF FILESYSTEM BUILDER & CDRECORD CD/DVD/BluRay CREATOR (C) 1993 E.YOUNGDALE (C) 1997 J.PEARSON/J.SCHILLING, iso_copyright_file_id: , iso_abstract_file_id: , iso_bibliographic_file_id: , iso_volume_creation_t: 1651087996, iso_volume_modification_t: 1651087996, iso_volume_expiration_t: -1, iso_volume_effective_t: 1651087996, >
test_isoinfo_device_0: test failed: expression false: STREQ (ret->iso_volume_id, "ISOIMAGE") && STREQ (ret->iso_volume_set_id, "") && ret->iso_volume_set_size == 1 && ret->iso_volume_sequence_number == 1 && ret->iso_logical_block_size == 2048
```

Full test log with trace:
[test-suite.log](https://github.com/libguestfs/libguestfs/files/8577470/test-suite.log)

The only way to pass the test is to either disable the test or change the default(?) in the generated function https://github.com/libguestfs/libguestfs/blob/ef8c6593eb4ab232891aeb6f144cf275a40efcbf/generator/actions_core.ml#L6832 and tests/c-api/tests.c (which... seems to be generated here: https://github.com/libguestfs/libguestfs/blob/master/generator/tests_c_api.ml)

It looks as if the test has been broken with https://github.com/libguestfs/libguestfs/commit/bf28bc01dbb7933db0eb07fb26e542b00e3643a5

Is this project tested in CI against multiple target OS?

**Comment by rwmjones** [comment]
If you want to skip just this one test, use:
```
export SKIP_TEST_ISOINFO_DEVICE_0=1
```
You can put that line into a file called `localenv` in the build directory to make it permanent.

I wonder why `iso_volume_id` is `CDROM` for you?  I guess you're using original `mkisofs`?

**Comment by rwmjones** [comment]
Possibly something like this would work:
```
diff --git a/generator/actions_core.ml b/generator/actions_core.ml
index e757140aaa..23a2eabef8 100644
--- a/generator/actions_core.ml
+++ b/generator/actions_core.ml
@@ -6829,7 +6829,8 @@ this will create the largest possible LV." };
     tests = [
       InitNone, Always, TestResult (
         [["isoinfo_device"; "/dev/sdd"]],
-          "STREQ (ret->iso_volume_id, \"ISOIMAGE\") && "^
+          "(STREQ (ret->iso_volume_id, \"CDROM\") || "^
+          " STREQ (ret->iso_volume_id, \"ISOIMAGE\")) && "^
           "STREQ (ret->iso_volume_set_id, \"\") && "^
           "ret->iso_volume_set_size == 1 && "^
           "ret->iso_volume_sequence_number == 1 && "^
```

**Comment by dvzrv** [comment]
> If you want to skip just this one test, use:
> 
> ```
> export SKIP_TEST_ISOINFO_DEVICE_0=1
> ```

Ah, very nice. Thanks!


> I wonder why `iso_volume_id` is `CDROM` for you? I guess you're using original `mkisofs`?

We have cdrtools available: https://github.com/archlinux/svntogit-community/blob/packages/cdrtools/trunk/PKGBUILD


> Possibly something like this would work:

Yes, that's what I'm doing right now.
