### ISSUE TITLE
Impossible to retreive :name attribute

### ISSUE THREAD

**Issue by Vadiml1024** [libguestfs/libguestfs#80]
It seems there is no way availabe in guestfish to retrieve the the value of *name* attribute specified when doing add-drive.
It would be nice to have an API which given a drive or partition will return the result of drive_to_string function...

**Comment by rwmjones** [comment]
I don't think the `name` field is actually used anywhere.  It was used by the old inspection code, but when that was moved to the daemon the hint was dropped (commit 3a00c4d179554f8c1299368a02b43370b6aa7af3).  See also: https://github.com/libguestfs/libguestfs/blob/0956e8e0c5b70e79a01f43046ac7be2b9a171ed8/daemon/inspect_fs_unix_fstab.ml#L495

We could certainly add an API to return the name field, but I'm not sure what good it will do.  If you're trying to store arbitrary data associated with each drive then it's likely better to store it in your own code.

**Comment by Vadiml1024** [comment]
My use case is following:
I'm adding LOT of files using add-drive and i need have a mapping back from
*device name* to the original file name.
And currently the only way to achieve it is to generate the a *label*
attribute for each add-drive and then to use
list_labels to get  device=>label mapping and maintain label=>filename
mapping by myself.
Which is unnecessary hassle given the fact that the info is already there.

**Comment by rwmjones** [comment]
What I mean is can you store your mapping elsewhere, such as an array of drives -> device name?  Anyway we can add an API to retrieve the `name` field if that's not possible.

**Comment by Vadiml1024** [comment]
The problem that *add-drive* does not return the *device name* which was
created!

**Comment by rwmjones** [comment]
OK I see, that's a slightly different understanding from what I thought.  You can just assume that devices added in order are called C</dev/sda>, C</dev/sdb> etc. (https://libguestfs.org/guestfs.3.html#block-device-naming).  If more than 26 devices are added then see: https://rwmj.wordpress.com/2011/01/09/how-are-linux-drives-named-beyond-drive-26-devsdz/

**Comment by rwmjones** [comment]
https://listman.redhat.com/archives/libguestfs/2022-April/028754.html
https://listman.redhat.com/archives/libguestfs/2022-April/028755.html
https://listman.redhat.com/archives/libguestfs/2022-April/028756.html

**Comment by rwmjones** [comment]
Alternatively ...
https://listman.redhat.com/archives/libguestfs/2022-April/028759.html

**Comment by Vadiml1024** [comment]
I was thinking about a function *list_disk_names* which will return an
output similar to list_disk_labels:
 hash table with *devicename* as key and *name* field as value

**Comment by rwmjones** [comment]
Isn't that `guestfs_list_devices`?

**Comment by rwmjones** [comment]
Can you save the list when you're adding them?  The problem is that no API could return what you want, but disks are more complicated than simple local files: https://libguestfs.org/guestfs.3.html#remote-storage

**Comment by Vadiml1024** [comment]
Well, what i'm doing right  now is something like:

labelmap = {}
label = 0
for pathName in files:
        labelmap[label] = guestinfo(file=pathName, dev="")
        ret = g.add_drive_opts(pathName, format="raw", readonly=True,
label=encode_number(label))
        print("g.add_drive_opts {pathName} = {ret}")
        label += 1

g.launch()
guest_labels = g.list_disk_labels()
for label,dev in enumerate(guest_labels):
     numeric_label = decode_number(label)
     labelmap[numeric_label].dev = dev


It works
