### ISSUE TITLE
line 6: syntax error near unexpected token `|'

### ISSUE THREAD

**Issue by unitythemaker** [libguestfs/libguestfs#81]
Hi! I'm getting an error when running this:
I've an Artix Linux installation.
I first tried installing libguestfs via pacman but it's failed because of a dependency named systemd-sysvcompat:
```
resolving dependencies...
warning: cannot resolve "systemd-sysvcompat", a dependency of "libguestfs"
:: The following package cannot be upgraded due to unresolvable dependencies:
      libguestfs

:: Do you want to skip the above package for this upgrade? [y/N]
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'systemd-sysvcompat' required by libguestfs
```
Then tried installing libguestfs-dev libguestfs-git and this repository but it failed with the error below:

Instructions: https://github.com/libguestfs/libguestfs/blob/master/docs/guestfs-building.pod#building-from-git
Error:
```
  OCAMLCMI inspect.cmi
  OCAMLOPT inspect.cmx
  OCAMLCMI rpm.cmi
  OCAMLOPT rpm.cmx
  OCAMLCMI callbacks.cmi
  OCAMLOPT callbacks.cmx
  OCAMLCMI daemon.cmi
  OCAMLOPT daemon.cmx
ocamlfind opt -output-obj -o camldaemon.o \
    -g -annot  -warn-error +C+D+E+F+L+M+P+S+U+V+Y+Z+X+52-3-6 -w -6 -ccopt '-fPIC -fno-strict-overflow -Wno-strict-overflow' -package str,unix,hivex -I ../bundled/ocaml-augeas -I ../common/mlstdutils -I ../common/mlutils -I ../common/utils/.libs -I ../common/mlpcre -I ../common/mlpcre/.libs -I ../gnulib/lib/.libs \
    -linkpkg \
    mlaugeas.cmxa \
    mlpcre.cmxa \
    mlstdutils.cmxa \
    mlcutils.cmxa \
    daemon_config.cmx utils.cmx structs.cmx optgroups.cmx sysroot.cmx mountable.cmx chroot.cmx blkid.cmx btrfs.cmx cryptsetup.cmx devsparts.cmx file.cmx filearch.cmx isoinfo.cmx is.cmx ldm.cmx link.cmx lvm.cmx lvm_utils.cmx lvm_dm.cmx findfs.cmx md.cmx mount.cmx mount_utils.cmx parted.cmx listfs.cmx realpath.cmx statvfs.cmx inspect_types.cmx inspect_utils.cmx inspect_fs_unix_fstab.cmx inspect_fs_unix.cmx inspect_fs_windows.cmx inspect_fs.cmx inspect.cmx rpm.cmx callbacks.cmx daemon.cmx
  CCLD     guestfsd
  POD      stamp-guestfsd.pod
touch stamp-guestfsd.pod
make[3]: Leaving directory '/home/unitythemaker/TMP/libguestfs/libguestfs/daemon'
make[2]: Leaving directory '/home/unitythemaker/TMP/libguestfs/libguestfs/daemon'
Making all in appliance
make[2]: Entering directory '/home/unitythemaker/TMP/libguestfs/libguestfs/appliance'
  POD      stamp-libguestfs-make-fixed-appliance.pod
touch stamp-libguestfs-make-fixed-appliance.pod
cd .. && \
  ./config.status --file=appliance/make.sh-t:appliance/make.sh.in
config.status: creating appliance/make.sh-t
chmod +x make.sh-t
cmp -s make.sh make.sh-t || mv make.sh-t make.sh
rm -f make.sh-t
/sbin/ldconfig -p > ld.so.cache.txt
objdump -p ../daemon/guestfsd |\
	sed -ne '/NEEDED/{s/ *NEEDED *//; p;}' |\
	xargs -i grep -F {} ld.so.cache.txt |\
	sed -ne '/ => /{s/.* => *//; p;}' |\
	 |\
	sort -u > guestfsd.deps.t
/bin/sh: -c: line 6: syntax error near unexpected token `|'
/bin/sh: -c: line 6: `	sort -u > guestfsd.deps.t'
make[2]: *** [Makefile:1100: guestfsd.deps] Error 2
make[2]: Leaving directory '/home/unitythemaker/TMP/libguestfs/libguestfs/appliance'
make[1]: *** [Makefile:1084: all-recursive] Error 1
make[1]: Leaving directory '/home/unitythemaker/TMP/libguestfs/libguestfs'
make: *** [Makefile:990: all] Error 2
```

**Comment by unitythemaker** [comment]
I cannot install systemd-sysvcompat because I've runit and to installing systemd-sysvcompat conflicts with so many packages I've.
```
➜  ~ paru -S systemd-sysvcompat                                                                                                                                            07:15:49
:: Resolving dependencies...
:: There are 4 providers available for systemd-sysvcompat:
:: Repository AUR:
    1) runit-conversion  2) systemd-sysvcompat-git  3) systemd-sysvcompat-homed-containers  4) systemd-sysvcompat-selinux
Enter a number (default=1): 1
:: Calculating conflicts...
:: Calculating inner conflicts...

:: Conflicts found:
    runit-conversion: lightdm-optimus-runit (systemd-sysvcompat)  sddm-optimus-runit (systemd-sysvcompat)

:: Conflicting packages will have to be confirmed manually

Aur (1) runit-conversion-9-1

:: Proceed to review? [Y/n]:

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: runit-conversion 9-1 (Cum 29 Nis 2022 07:16:01)
==> Retrieving sources...
  -> Found runit-conversion-9.tar.gz
==> Validating source files with sha256sums...
    runit-conversion-9.tar.gz ... Passed
==> Making package: runit-conversion 9-1 (Cum 29 Nis 2022 07:16:01)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found runit-conversion-9.tar.gz
==> Validating source files with sha256sums...
    runit-conversion-9.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting runit-conversion-9.tar.gz with bsdtar
==> Sources are ready.
runit-conversion-9-1: parsing pkg list...
:: runit-conversion-9-1 is up to date -- skipping build
loading packages...
resolving dependencies...
looking for conflicting packages...
:: runit-conversion and lightdm-optimus-runit are in conflict (systemd-sysvcompat). Remove lightdm-optimus-runit? [y/N] N
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: runit-conversion and lightdm-optimus-runit are in conflict
```

**Comment by rwmjones** [comment]
What does this have to do with libguestfs?

**Comment by unitythemaker** [comment]
> What does this have to do with libguestfs?

I can't build nor install it due to make errors.

**Comment by unitythemaker** [comment]
I didn't check it but it works now.
Thank you so much!

**Comment by SDRausty** [comment]
> I pushed these patches which fix things for me: [libguestfs/supermin@e5cd10f](https://github.com/libguestfs/supermin/commit/e5cd10fc0952da1c51eb7b762fe19d54b2ec1e8d) [libguestfs/supermin@c9ddb96](https://github.com/libguestfs/supermin/commit/c9ddb9648b3b810aa50fc238edb5fe55df9643b6) [f9babf8](https://github.com/libguestfs/libguestfs/commit/f9babf8c04e0d471ba7bea0eced5105a274d2ddb)

I have got successfull builds on QEMU emulated `x86` and `x86_64` in `aarch64` in Arch Linux.  Can you please also add `aarch64` support with a similar commit @rwmjones?

**Comment by SDRausty** [comment]
> I pushed these patches which fix things for me: [libguestfs/supermin@e5cd10f](https://github.com/libguestfs/supermin/commit/e5cd10fc0952da1c51eb7b762fe19d54b2ec1e8d) [libguestfs/supermin@c9ddb96](https://github.com/libguestfs/supermin/commit/c9ddb9648b3b810aa50fc238edb5fe55df9643b6) [f9babf8](https://github.com/libguestfs/libguestfs/commit/f9babf8c04e0d471ba7bea0eced5105a274d2ddb)

Thank you!  I have got successfull builds with QEMU emulated `x86` and `x86_64` in `aarch64` in Arch Linux in [TermuxArch](https://termuxarch.github.io/TermuxArch/) with [`makelibguestfs`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L685&&#L743).  The build fails with the same error, "line 6: syntax error near unexpected token \`|'" on straight `aarch64` without architecture emulation.  Can you please also add `aarch64` support with a similar patch @rwmjones?

**Comment by SDRausty** [comment]
>the full error on aarch64? 

This error is now resolved.  THANK YOU!

**Comment by SDRausty** [comment]
>the full error on aarch64?

>This is the next error to arrise "line 6: syntax error near unexpected token `|'":
![Screenshot_20220504-172705](https://user-images.githubusercontent.com/27742457/166828810-9e60a95e-c9a3-4e13-bc6a-b0af964f9855.png)


`POD      stamp-guestfsd.pod
touch stamp-guestfsd.pod
make[3]: Leaving directory '/home/sdrausty/libguestfs/daemon'
make[2]: Leaving directory '/home/sdrausty/libguestfs/daemon'
Making all in appliance
make[2]: Entering directory '/home/sdrausty/libguestfs/appliance'
  POD      stamp-libguestfs-make-fixed-appliance.pod
touch stamp-libguestfs-make-fixed-appliance.pod
cd .. && \
  ./config.status --file=appliance/make.sh-t:appliance/make.sh.in
config.status: creating appliance/make.sh-t
chmod +x make.sh-t
cmp -s make.sh make.sh-t || mv make.sh-t make.sh
rm -f make.sh-t
/sbin/ldconfig -p > ld.so.cache.txt
objdump -p ../daemon/guestfsd |\
        sed -ne '/NEEDED/{s/ *NEEDED *//; p;}' |\
        xargs -i grep -F {} ld.so.cache.txt |\
        sed -ne '/ => /{s/.* => *//; p;}' |\
         |\
        sort -u > guestfsd.deps.t
/bin/sh: -c: line 6: syntax error near unexpected token `|'
/bin/sh: -c: line 6: `  sort -u > guestfsd.deps.t'
make[2]: *** [Makefile:1100: guestfsd.deps] Error 2
make[2]: Leaving directory '/home/sdrausty/libguestfs/appliance'
make[1]: *** [Makefile:1085: all-recursive] Error 1
make[1]: Leaving directory '/home/sdrausty/libguestfs'
make: *** [Makefile:991: all] Error 2
TermuxArch command 'makelibguestfs' version 2.1.653 [Exit Signal 169]: DONE  🏁`

>Any suggestions for this unexpected token?

_Originally posted by @SDRausty in https://github.com/libguestfs/libguestfs/issues/82#issuecomment-1117963661_

This error is now resolved in TermuxArch on x86, x86_64 and aarch64 architectures.

**Comment by SDRausty** [comment]
> > the full error on aarch64?
> 
> This error is now resolved in TermuxArch on x86, x86_64 and aarch64 architectures. THANK YOU!

~~This error is now resolved in TermuxArch on x86, x86_64 and aarch64 architectures.~~ THANK YOU!

It is back:
>Making all in appliance
make[2]: Entering directory '/home/sdrausty/libguestfs/appliance'
cd .. && \
  ./config.status --file=appliance/make.sh-t:appliance/make.sh.in
config.status: creating appliance/make.sh-t
chmod +x make.sh-t
cmp -s make.sh make.sh-t || mv make.sh-t make.sh
rm -f make.sh-t
/sbin/ldconfig -p > ld.so.cache.txt
objdump -p ../daemon/guestfsd |\
        sed -ne '/NEEDED/{s/ *NEEDED *//; p;}' |\
        xargs -i grep -F {} ld.so.cache.txt |\
        sed -ne '/ => /{s/.* => *//; p;}' |\
         |\
        sort -u > guestfsd.deps.t
/bin/sh: -c: line 6: syntax error near unexpected token `|'
/bin/sh: -c: line 6: `  sort -u > guestfsd.deps.t'
make[2]: *** [Makefile:1100: guestfsd.deps] Error 2
make[2]: Leaving directory '/home/sdrausty/libguestfs/appliance'
make[1]: *** [Makefile:1085: all-recursive] Error 1
make[1]: Leaving directory '/home/sdrausty/libguestfs'
make: *** [Makefile:991: all] Error 2
sdrausty11:52libguestfs$ um
aarch64

Can you fix it again please?

**Comment by rwmjones** [comment]
The problem is that the `QUERY_FILES_CMD` variable isn't getting expanded.  I don't know why that happens, maybe `DISTRO` isn't being set.  Anyway there's not enough information for me to tell what is going on because I don't see the complete output from `./configure`.  You may be better off just tracing the code yourself:
https://github.com/libguestfs/libguestfs/blob/bf5fcdbc9b845b56ad4cd2ed4582959817e4846e/m4/guestfs-appliance.m4#L90-L128
https://github.com/libguestfs/libguestfs/blob/bf5fcdbc9b845b56ad4cd2ed4582959817e4846e/appliance/Makefile.am#L83-L91

**Comment by SDRausty** [comment]
>tracing the code

[[ARCH | MANJARO | ARTIX],[DISTRO=ARCHLINUX],](https://github.com/libguestfs/libguestfs/blob/master/m4/guestfs-appliance.m4#L111)

This BASH function is being tested:

[\_PHLIBGUESTFS_(){ [ -f /etc/os-release ] && TMRCMDVL="\$(grep -w ID /etc/os-release | cut -d"=" -f 2)" && sed -Ei "s/ARCH\ \|\ MANJARO\ \|/\${TMRCMDVL^^}\ \|\ MANJARO\ \|/g" m4/guestfs-appliance.m4 ; }](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L923)

![Screenshot_20220522-123623](https://user-images.githubusercontent.com/27742457/169706392-5ef55c42-0610-4569-8258-98aefe46fd8a.png)

>PRETTY_NAME="Arch Linux 32"
ID=arch32
ID_LIKE=arch

Have you considered using ID_LIKE if exists in file /etc/os-release as a potential resolution?

**Comment by rwmjones** [comment]
Can you try this one? https://listman.redhat.com/archives/libguestfs/2022-May/028941.html

**Comment by SDRausty** [comment]
>Can you try this one? https://listman.redhat.com/archives/libguestfs/2022-May/028941.html

Thank you for sharing;  I am presently testing this patch (in TermuxArch with and without [`makelibguestfs`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L715&&#L941) on an old Android smartphone (circa 2019 product) in three architectures, one in Termux PRoot and two in Termux PRoot with QEMU emulation; e.g. x86, x86_64 and aarch64)...

**Comment by SDRausty** [comment]
Testing `libguestfs` on an Android smartphone with TermuxArch:

https://user-images.githubusercontent.com/27742457/169723327-7949fa9f-faed-4ef9-9fa0-31dfc6164790.mp4

>testing this patch

today:
![Screenshot_20220522-203107](https://user-images.githubusercontent.com/27742457/169723342-17d3f47c-87a4-47a4-aaa7-097f086ec116.png)

**Comment by SDRausty** [comment]
hot off the press:

![Screenshot_20220522-205002](https://user-images.githubusercontent.com/27742457/169724268-15f76d2f-1771-4fba-afce-3b851820017d.png)
