### ISSUE TITLE
make[2]: *** No rule to make target 'guestfs_protocol.c', needed by 'all'.  Stop.

### ISSUE THREAD

**Issue by SDRausty** [libguestfs/libguestfs#82]
make[3]: Entering directory '/home/sdrausty/libguestfs/common/errnostring'
  CC       liberrnostring_la-errnostring-gperf.lo
  CC       liberrnostring_la-errnostring.lo
  CCLD     liberrnostring.la
make[3]: Leaving directory '/home/sdrausty/libguestfs/common/errnostring'
make[2]: Leaving directory '/home/sdrausty/libguestfs/common/errnostring'
Making all in common/protocol
make[2]: Entering directory '/home/sdrausty/libguestfs/common/protocol'
make[2]: *** No rule to make target 'guestfs_protocol.c', needed by 'all'.  Stop.
![Screenshot_20220504-115446](https://user-images.githubusercontent.com/27742457/166723019-8655f1c5-544c-4923-9510-ec5b00232014.png)

make[2]: Leaving directory '/home/sdrausty/libguestfs/common/protocol'
make[1]: *** [Makefile:1085: all-recursive] Error 1
make[1]: Leaving directory '/home/sdrausty/libguestfs'                            make: *** [Makefile:991: all] Error 2

 ＴｅｒｍｕｘＡｒｃｈ MAKELIBGUESTFS NOTICE:  Generated script signal 2 near or at line number 68 by 'make'!

TermuxArch command 'makelibguestfs' version 2.1.646 [Exit Signal 2]: DONE  🏁
sdrausty11:51~$ um
i686

**Comment by rwmjones** [comment]
That file is generated by `rpcgen` so you'll have to find and install that tool.

**Comment by SDRausty** [comment]
>file is generated by `rpcgen`

Thank you very much for this important information @rwmjones 🎼  The Arch Linux `rpcsvc-proto` package has `rpcgen`.  This is the next error to arrise `line 6: syntax error near unexpected token '|'`:
![Screenshot_20220504-172705](https://user-images.githubusercontent.com/27742457/166828810-9e60a95e-c9a3-4e13-bc6a-b0af964f9855.png)


>POD      stamp-guestfsd.pod
touch stamp-guestfsd.pod
make[3]: Leaving directory '/home/sdrausty/libguestfs/daemon'
make[2]: Leaving directory '/home/sdrausty/libguestfs/daemon'
Making all in appliance
make[2]: Entering directory '/home/sdrausty/libguestfs/appliance'
  POD      stamp-libguestfs-make-fixed-appliance.pod
touch stamp-libguestfs-make-fixed-appliance.pod
cd .. && \
  ./config.status --file=appliance/make.sh-t:appliance/make.sh.in
config.status: creating appliance/make.sh-t
chmod +x make.sh-t
cmp -s make.sh make.sh-t || mv make.sh-t make.sh
rm -f make.sh-t
/sbin/ldconfig -p > ld.so.cache.txt
objdump -p ../daemon/guestfsd |\
        sed -ne '/NEEDED/{s/ *NEEDED *//; p;}' |\
        xargs -i grep -F {} ld.so.cache.txt |\
        sed -ne '/ => /{s/.* => *//; p;}' |\
         |\
        sort -u > guestfsd.deps.t
/bin/sh: -c: line 6: syntax error near unexpected token `|'
/bin/sh: -c: line 6: `  sort -u > guestfsd.deps.t'
make[2]: *** [Makefile:1100: guestfsd.deps] Error 2
make[2]: Leaving directory '/home/sdrausty/libguestfs/appliance'
make[1]: *** [Makefile:1085: all-recursive] Error 1
make[1]: Leaving directory '/home/sdrausty/libguestfs'
make: *** [Makefile:991: all] Error 2
TermuxArch command 'makelibguestfs' version 2.1.653 [Exit Signal 169]: DONE  🏁

Any suggestions for this unexpected pipe?

**Comment by BH1SCW** [comment]
> > file is generated by `rpcgen`
> 
> Thank you very much for this important information @rwmjones 🎼 The Arch Linux `rpcsvc-proto` package has `rpcgen`. This is the next error to arrise "line 6: syntax error near unexpected token `|'": ![Screenshot_20220504-172705](https://user-images.githubusercontent.com/27742457/166828810-9e60a95e-c9a3-4e13-bc6a-b0af964f9855.png)
> 
> `POD stamp-guestfsd.pod touch stamp-guestfsd.pod make[3]: Leaving directory '/home/sdrausty/libguestfs/daemon' make[2]: Leaving directory '/home/sdrausty/libguestfs/daemon' Making all in appliance make[2]: Entering directory '/home/sdrausty/libguestfs/appliance' POD stamp-libguestfs-make-fixed-appliance.pod touch stamp-libguestfs-make-fixed-appliance.pod cd .. && \ ./config.status --file=appliance/make.sh-t:appliance/make.sh.in config.status: creating appliance/make.sh-t chmod +x make.sh-t cmp -s make.sh make.sh-t || mv make.sh-t make.sh rm -f make.sh-t /sbin/ldconfig -p > ld.so.cache.txt objdump -p ../daemon/guestfsd |\ sed -ne '/NEEDED/{s/ *NEEDED *//; p;}' |\ xargs -i grep -F {} ld.so.cache.txt |\ sed -ne '/ => /{s/.* => *//; p;}' |\ |\ sort -u > guestfsd.deps.t /bin/sh: -c: line 6: syntax error near unexpected token `|' /bin/sh: -c: line 6: ` sort -u > guestfsd.deps.t' make[2]: *** [Makefile:1100: guestfsd.deps] Error 2 make[2]: Leaving directory '/home/sdrausty/libguestfs/appliance' make[1]: *** [Makefile:1085: all-recursive] Error 1 make[1]: Leaving directory '/home/sdrausty/libguestfs' make: *** [Makefile:991: all] Error 2 TermuxArch command 'makelibguestfs' version 2.1.653 [Exit Signal 169]: DONE 🏁`
> 
> Any suggestions for this unexpected token?

so what is workaround or fix for this error?  I also meet this error today.

/bin/sh: -c: line 5: syntax error near unexpected token `|'
/bin/sh: -c: line 5: `	sort -u > guestfsd.deps.t'

**Comment by rwmjones** [comment]
The problem happens here:
https://github.com/libguestfs/libguestfs/blob/c2dd84b2635bb2d9f7fb0b4ecf1e0274bfd553b1/appliance/Makefile.am#L103
because QUERY_FILES_CMD hasn't been set.
https://github.com/libguestfs/libguestfs/blob/c2dd84b2635bb2d9f7fb0b4ecf1e0274bfd553b1/appliance/Makefile.am#L91
tells you what you have to do to fix it.

**Comment by BH1SCW** [comment]
@rwmjones  wow, so nice thanks a million！
