### ISSUE TITLE
No Manual for Guestfish

### ISSUE THREAD

**Issue by SDRausty** [libguestfs/libguestfs#85]
I am finding these errors:  `seems outdated (The amount of entries differ between files:`
![Screenshot_20220517-075747](https://user-images.githubusercontent.com/27742457/168806032-09527c64-7fa5-46b6-b89e-37fb5dcd4e32.png)

This error still persists: `No manual entry for guestfish in section 1`
![Screenshot_20220517-075944](https://user-images.githubusercontent.com/27742457/168806250-9b7fd92b-494c-4358-827c-b1fdc2243dd7.png)

I have tried using `po4a-updatepo` unsuccessfully.  Can an `info` command also be added to libguestfs?  More relevantly to this issue here, what can be done to complete the libguestfs manual build?

**Comment by rwmjones** [comment]
You can use `man ./fish/guestfish.1` to read the manual.

**Comment by SDRausty** [comment]
>Makefile:1096: *** Error: Unknown Linux distribution "ARCH".  Please add support to m4/guestfs-appliance.m4 and appliance/Makefile.am and send a patch upstream to libguestfs@redhat.com. Stop.

This is the result I currently get.

**Comment by SDRausty** [comment]
>You can use `man ./fish/guestfish.1` to read the manual.

![Screenshot_20220605-193031](https://user-images.githubusercontent.com/27742457/172075161-5b3a2f4d-9316-4516-89bf-7f95fa03ab2e.png)


Yes, now I can;  Thank you!
