### ISSUE TITLE
supermin: packages specified on the command line:

### ISSUE THREAD

**Issue by SDRausty** [libguestfs/libguestfs#89]
[> supermin: packages specified on the command line:](https://www.ecosia.org/search?q=supermin%3A%20packages%20specified%20on%20the%20command%20line%3A)

```
sdrausty13:01libguestfs$ pcss supermin
community/supermin 5.3.1-1 [installed]
    Tool for creating supermin appliances
```

I am using [`makelibguestfs`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L711&&L955) to build `libguestfs` on my Android smartphone in TermuxArch and `supermin` still wants to download Arch Linux packages that are already installed if I strike `--disable-appliance --disable-daemon` from the build instructions;  How can `supermin` be told not to download anything during compile time?

**Comment by SDRausty** [comment]
Possibly `--needed` should be added so `supermin` does NOT download and install packages that are already present in the Arch Linux system.  I looked through the code looming for where `--needed` can be added, and was not successful in adding it to the `pacman` statement.

**Comment by rwmjones** [comment]
supermin has to download or obtain some of the packages in order to get the unmodified configuration files, since the config files of installed packages may have been modified by the administrator.  There are two ways around this: `supermin --use-installed` will assume that the `/etc/` files are unmodified and use those; or do what Fedora does to provide a local repo if no network is available: https://src.fedoraproject.org/rpms/libguestfs/blob/rawhide/f/libguestfs.spec#_739

**Comment by SDRausty** [comment]
I have tried modifying some of the makefiles without success as the files I had modified were overwritten.  Can you please outline `localconfigure`, and how this file can be used to add `--use-installed` and `CFLAGS=-fPIC` into the build process?

**Comment by rwmjones** [comment]
```
$ ./configure --help
...
  --with-supermin-extra-options="--opt1 --opt2 ..."
                          Pass additional supermin options. [default=no]
```

You can configure libguestfs with something like:

```
./configure --with-supermin-extra-options="--use-installed"
```

I should note again that `-use-installed` is only correct to use when you can be sure that the `/etc/` files have not been modified.  There are only fairly narrow cases when this is true, such as building libguestfs within a pristine build system.

**Comment by SDRausty** [comment]
Thank you for supplying crucial information:
>the /etc/ files have not been modified
