### ISSUE TITLE
go import "libguestfs.org/guestfs"

### ISSUE THREAD

**Issue by 1429178646** [libguestfs/libguestfs#90]
I'm a rookie, while import on goland, the error is
	libguestfs.org/guestfs: cannot find module providing package libguestfs.org/guestfs: unrecognized import path "libguestfs.org/guestfs": reading https://libguestfs.org/guestfs?go-get=1: 404 Not Found
thank you

**Comment by rwmjones** [comment]
It's best to copy the bindings from the source tarball for now.  We don't host them anywhere.

**Comment by rwmjones** [comment]
I would suggest getting the source tarball: https://download.libguestfs.org/1.49-development/

Unpack that and you'll find golang bindings in the `golang/src/` subdirectory.

**Comment by 1429178646** [comment]
umm, I copied folder libguestfs.org to src folder，but goland reminds me of my lack of guestfs.h, so I copied guestfs.h in 1.49 to libguestfs.org/guestfs/   ,but goland  error:
D:/Program Files (x86)/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lguestfs
collect2.exe: error: ld returned 1 exit status
what should  I do next, thank you very much

**Comment by 1429178646** [comment]
![3DE%7$D_8~CBO2Y EN7K2C](https://user-images.githubusercontent.com/49406525/173294797-f64846fc-0392-4782-b196-8b7820cb0e95.png)

**Comment by 1429178646** [comment]
![8U3OTZG9}WN3KD2YDW_9V8X](https://user-images.githubusercontent.com/49406525/173295102-1bdc0641-ea13-453d-9465-9c59c4f1575b.png)

**Comment by rwmjones** [comment]
I don't know how golang works, but you should be able to install libguestfs library and headers by doing: `sudo yum install libguestfs-devel`

**Comment by 1429178646** [comment]
![image](https://user-images.githubusercontent.com/49406525/173345947-c933f493-f99b-4ef7-8496-4efeac50d2f5.png)

**Comment by 1429178646** [comment]
thanks ，but after sudo yum install libguestfs-devel，the new error (ㄒoㄒ)
