### ISSUE TITLE
Use on macOS

### ISSUE THREAD

**Issue by aparcar** [libguestfs/libguestfs#94]
I find very little documentation on using libguestfs on macOS, there is just a fairly outdated [brew configuration](https://github.com/zchee/homebrew-libguestfs/blob/master/libguestfs.rb) somewhere.

Are there official docs giving more details?

**Comment by rwmjones** [comment]
You'll need to try it, we don't have any macOS machines to use for development or any documentation.

**Comment by aparcar** [comment]
Is there any interest to support this? If so I'd try to figure things out and post possible finding here.

**Comment by rwmjones** [comment]
Sure, it did work at some point in the past.

**Comment by giovariot** [comment]
@rwmjones could you share your process?
