### ISSUE TITLE
OpenSUSE dead image link renders virt-builder completely unusable

### ISSUE THREAD

**Issue by eskultety** [libguestfs/libguestfs#99]
It appears OpenSUSE has sunset the virt-builder image [repo](http://download.opensuse.org/repositories/Virtualization:/virt-builder-images/images/index)

causing even basic virt-builder functionality to end with a fatal error:

```
$ virt-builder --list
 virt-builder: error: failed to download 
http://download.opensuse.org/repositories/Virtualization:/virt-builder-images/images/index: 
HTTP status code 404
```
This breaks upstream libvirt integration CI. The workaround is to comment the URL in `/etc/virt-builder/repos.d/opensuse.conf`
Note that fixing this properly will result in addressing https://github.com/libguestfs/libguestfs/issues/92 as well.

**Comment by eskultety** [comment]
reported in the upstream tracker as well: https://bugzilla.redhat.com/show_bug.cgi?id=2144461

**Comment by rwmjones** [comment]
Yup, let's remove the repo upstream for now, and ask OpenSUSE if they're going to bring it back.
^^ @olafhering @cbosdo

**Comment by rwmjones** [comment]
https://github.com/rwmjones/guestfs-tools/commit/8e0e91c923bd7076fd906a71678ddd3f328ae2c0

**Comment by berrange** [comment]
Should virt-builder just print a warning about the failed metadata download and carry on. If the requested image actually belonged to the dead repo, then it will get an fatal error eventually, and if it didn't belong to that repo, everything is good.
This is what dnf/yum do if they can't download a particular repo.

**Comment by rwmjones** [comment]
Yes it's current behaviour with dead repos is not that great.  dnf has `skip_if_unavailable` which would be nice to implement here.

**Comment by olafhering** [comment]
https://download.opensuse.org/repositories/Virtualization:/virt-builder-images/images/ is back.
I lifted the image from 2015 to 2022. It will likely need some love to become fully usable.
